<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>TSKAtkInspector</AssemblyName>
    <Version>1.8.2</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src/*.cs" />
    <Reference Include="BepInEx.Core"><HintPath>../../BepInEx/core/BepInEx.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Unity.IL2CPP"><HintPath>../../BepInEx/core/BepInEx.Unity.IL2CPP.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>../../BepInEx/core/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.Runtime"><HintPath>../../BepInEx/core/Il2CppInterop.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="../../BepInEx/interop/*.dll"><Private>false</Private></Reference>
  </ItemGroup>
</Project>
